server:
    port: 8082
spring:
    application:
        name: notification
    datasource:
        url: jdbc:postgresql://localhost:5432/notification
        username: trroooyyyy
        password: "06062023"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true




