server:
    port: 8082
spring:
    application:
        name: notification
    datasource:
        url: jdbc:postgresql://localhost:5432/notification
        username: trroooyyyy
        password: "06062023"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-group
eureka:
    client:
        service-url:
            defaultZone=http://localhost:8761/eureka/:



