spring:
    application:
        name: currency-exchange
    profiles:
        active: dev
    config:
        import: "configserver:http://localhost:8888"
    cloud:
        config:
            fail-fast: true