management:
    endpoints:
        web:
            exposure:
                include: refresh, health, info, env
spring:
    application:
        name: ANB
    cloud:
        config:
            fail-fast: true
    config:
        import: configserver:http://localhost:8888
    profiles:
        active: dev
