spring:
    application:
        name: ANB
    profiles:
        active: dev
    config:
        import: "configserver:http://localhost:8888"
    cloud:
        config:
            fail-fast: true
management:
    endpoints:
        web:
            exposure:
                include: refresh, health, info, env