server:
    port: 8080
spring:
    application:
        name: ANB
    datasource:
        url: jdbc:postgresql://localhost:5432/ANB
        username: trroooyyyy
        password: "06062023"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
currency-service:
        url: http://localhost:8081/api/v1/ce/getExchangedValue
notification-service:
        url: http://localhost:8082/api/v1/notification/
transaction-service:
        url: http://localhost:8083/api/v1/transactions/


