server:
    port: 8083
spring:
    application:
        name: transaction-processor
    datasource:
        url: jdbc:postgresql://localhost:5432/transaction-processor
        username: trroooyyyy
        password: "06062023"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
currency-service:
    url: http://localhost:8081/api/v1/ce/getExchangedValue
account-service:
    url: http://localhost:8080/api/v1/accounts




